---
# tasks file for roles/webservers

# Debug password from secret file
- name: Use secret password here
  debug:
    msg: "{{ secret_password }}"

- name: See directory contents
  command: ls -la {{ path_to_app }}
  register: dir_contents

- name: Debug directory contents
  debug:
    msg: "{{ dir_contents }}"

- name: Configure php.ini
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=On'
  notify:
      - Restart Apache