---
# tasks file for roles/webservers

# Debug password from secret file
- name: Use secret password here
  debug:
    msg: "{{ secret_password }}"


# Copy php aplication files into webservers
- name: Copying web.php file to webservers
  copy:
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 0755
  tags: upload

- name: Create simple info page
  copy:
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> Info about webserver {{ ansible_hostname }} </h1>"
  tags: create

- name: See directory contents
  command: ls -la {{ path_to_app }}
  register: dir_contents

- name: Debug directory contents
  debug:
    msg: "{{ dir_contents }}"

- name: Configure php.ini
  lineinfile:
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=On'
  notify:
      - Restart Apache