# Create two apache+php servers with initial configuration and configure load balancer
---
  - hosts: webservers
    become: true
    tasks:
      - name: Installing Apache and PHP on webservers
        package:
          name: 
            - httpd
            - php
          state: latest
      - name: Enabling Apache service on webservers
        service:
          name: httpd
          state: started
          enabled: yes
          
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing Apache on loadbalancers
        package:
          name: 
            - httpd
          state: latest
      - name: Enabling Apache service on loadbalancers
        service:
          name: httpd
          state: started
          enabled: yes