# Copy php aplication files into webservers
---
  - hosts: webservers
    become: true

    vars:
      path_to_app: "/var/www/hmtl"

    tasks:
    - name: Copying web.php file to webservers
      copy:
        src: ../index.php
        dest: "{{ path_to_app }}"
        mode: 0755

    - name: Create simple info page
      copy:
        dest: "{{ path_to_app }}/info.php"
        content: "<h1> Info about webserver {{ ansible_hostname }} </h1>"

    - name: Configure php.ini
      lineinfile:
        path: /etc/php.ini
        regexp: ^short_open_tag
        line: 'short_open_tag=On'
      notify:
          - Restart Apache
    handlers:
      - name: Restart Apache
        service: 
          name: httpd
          state: restarted