# Copy php aplication files into webservers
---
  - hosts: webservers
    become: true
    roles:
      - webservers
    
    vars_prompt:
      - name: "upload_var"
        prompt: "Upload the index.php file?"
      - name: "create_var"
        prompt: "Create info.php page?"