# Copy php aplication files into webservers
---
  - hosts: webservers
    tasks:
    - name: Copying web.php file to webservers
      copy:
        src: ../index.php
        dest: /var/www/html
        mode: 0755