# Copy php aplication files into webservers
---
  - hosts: webservers
    become: true
    tasks:
    - name: Copying web.php file to webservers
      copy:
        src: ../index.php
        dest: /var/www/html
        mode: 0755
    - name: Configure php.ini
      lineinfile:
        path: /etc/php.ini
        regexp: ^short_open_tag
        line: 'short_open_tag=On'
    - name: Restart apache
      service:
        name: httpd
        state: restarted