# Set up loadbalancer configuration
---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Creating tamplate
        template:
        src: ../config/lb-config.j2
        dest: /etc/httpd/conf.d/lb.config
        owner: bin
        group: wheel
        mode: 064

      - name: Restart Apache
        service: 
          name: httpd
          state: restarted